[package]
name = "kiln-net"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
kiln-link.workspace = true
kiln-proto.workspace = true
kiln-data.workspace = true
aes.workspace = true
anyhow.workspace = true
bytes.workspace = true
cfb8.workspace = true
crossbeam-channel.workspace = true
hmac.workspace = true
md-5.workspace = true
rand_core.workspace = true
rsa.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
subtle.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
ureq.workspace = true
uuid = { workspace = true, features = ["v4"] }
