//! Per-state block facts extracted from the vanilla game (light, collision, hardness, ...),
//! embedded as a compact table generated by `cargo xtask extract && cargo xtask codegen`.

use std::sync::OnceLock;

static RAW: &[u8] = include_bytes!("gen/block_props.bin");

/// Axis-aligned box in block-local coordinates (0..1): min x, y, z, max x, y, z.
pub type Aabb = [f32; 6];

#[derive(Clone, Copy)]
struct Entry {
    light: u8,
    flags: u16,
    faces: u8,
    hardness: f32,
    shape: u16,
}

struct Table {
    states: Vec<Entry>,
    shapes: Vec<Vec<Aabb>>,
}

fn table() -> &'static Table {
    static TABLE: OnceLock<Table> = OnceLock::new();
    TABLE.get_or_init(|| {
        assert_eq!(&RAW[..4], b"KBP1", "block_props.bin: bad magic");
        let n = u32::from_le_bytes(RAW[4..8].try_into().unwrap()) as usize;
        let shape_count = u32::from_le_bytes(RAW[8..12].try_into().unwrap()) as usize;
        let mut p = 12;
        let mut states = Vec::with_capacity(n);
        for _ in 0..n {
            let e = &RAW[p..p + 10];
            states.push(Entry {
                light: e[0],
                flags: u16::from_le_bytes([e[1], e[2]]),
                faces: e[3],
                hardness: f32::from_le_bytes(e[4..8].try_into().unwrap()),
                shape: u16::from_le_bytes([e[8], e[9]]),
            });
            p += 10;
        }
        let mut shapes = Vec::with_capacity(shape_count);
        for _ in 0..shape_count {
            let count = RAW[p] as usize;
            p += 1;
            let mut boxes = Vec::with_capacity(count);
            for _ in 0..count {
                let mut b = [0f32; 6];
                for v in &mut b {
                    *v = f32::from_le_bytes(RAW[p..p + 4].try_into().unwrap());
                    p += 4;
                }
                boxes.push(b);
            }
            shapes.push(boxes);
        }
        assert_eq!(p, RAW.len(), "block_props.bin: trailing data");
        Table { states, shapes }
    })
}

fn entry(state: u16) -> Entry {
    table().states[state as usize]
}

const SKY_DOWN: u16 = 1 << 0;
const SHAPE_OCCLUDES: u16 = 1 << 1;
const CAN_OCCLUDE: u16 = 1 << 2;
const SOLID_RENDER: u16 = 1 << 3;
const REPLACEABLE: u16 = 1 << 6;
const RANDOM_TICKS: u16 = 1 << 7;
const BLOCK_ENTITY: u16 = 1 << 8;
const CORRECT_TOOL: u16 = 1 << 9;
const FULL_COLLISION: u16 = 1 << 10;

/// Light the block emits (0-15).
pub fn light_emission(state: u16) -> u8 {
    entry(state).light >> 4
}

/// How much light is reduced passing through the block (0-15).
pub fn light_dampening(state: u16) -> u8 {
    entry(state).light & 15
}

/// Sky light passes straight down through the block without loss.
pub fn propagates_skylight_down(state: u16) -> bool {
    entry(state).flags & SKY_DOWN != 0
}

/// Light occlusion depends on the block's face shapes (slabs, stairs, ...).
pub fn uses_shape_for_light_occlusion(state: u16) -> bool {
    entry(state).flags & SHAPE_OCCLUDES != 0
}

/// Whether the occlusion face toward direction `dir` (0 down .. 5 east) is a full square.
pub fn face_full(state: u16, dir: u8) -> bool {
    entry(state).faces & (1 << dir) != 0
}

pub fn can_occlude(state: u16) -> bool {
    entry(state).flags & CAN_OCCLUDE != 0
}

pub fn solid_render(state: u16) -> bool {
    entry(state).flags & SOLID_RENDER != 0
}

/// Replaced when a block is placed into it (air, water, tall grass, ...).
pub fn replaceable(state: u16) -> bool {
    entry(state).flags & REPLACEABLE != 0
}

pub fn randomly_ticks(state: u16) -> bool {
    entry(state).flags & RANDOM_TICKS != 0
}

pub fn has_block_entity(state: u16) -> bool {
    entry(state).flags & BLOCK_ENTITY != 0
}

pub fn requires_correct_tool(state: u16) -> bool {
    entry(state).flags & CORRECT_TOOL != 0
}

/// Destroy time (hardness); -1 for unbreakable blocks.
pub fn hardness(state: u16) -> f32 {
    entry(state).hardness
}

pub fn full_collision(state: u16) -> bool {
    entry(state).flags & FULL_COLLISION != 0
}

/// Collision boxes with an empty collision context.
pub fn collision(state: u16) -> &'static [Aabb] {
    &table().shapes[entry(state).shape as usize]
}

fn tag_members(registry: &str, tag: &str) -> Vec<bool> {
    let n = crate::blocks::STATE_COUNT as usize;
    let mut out = vec![false; n];
    let blocks = crate::registries::TAGS
        .iter()
        .find(|(r, _)| *r == registry)
        .and_then(|(_, tags)| tags.iter().find(|(t, _)| *t == tag))
        .map_or(&[][..], |(_, ids)| *ids);
    let names = crate::builtin_entries("minecraft:block").unwrap_or(&[]);
    for &id in blocks {
        if let Some(info) = names.get(id as usize).and_then(|n| crate::blocks_types::block_by_name(n)) {
            out[info.first as usize..=info.last as usize].fill(true);
        }
    }
    out
}

/// Counts toward the MOTION_BLOCKING heightmap (26.3: the `blocks_motion_in_heightmap`
/// tag, or a non-empty fluid).
pub fn motion_blocking(state: u16) -> bool {
    static T: OnceLock<Vec<bool>> = OnceLock::new();
    T.get_or_init(|| tag_members("minecraft:block", "minecraft:blocks_motion_in_heightmap"))[state as usize]
        || crate::blocks_types::has_fluid(state)
}

/// Counts toward the MOTION_BLOCKING_NO_LEAVES heightmap.
pub fn motion_blocking_no_leaves(state: u16) -> bool {
    static T: OnceLock<Vec<bool>> = OnceLock::new();
    T.get_or_init(|| tag_members("minecraft:block", "minecraft:blocks_motion_in_heightmap_no_leaves"))[state as usize]
        || crate::blocks_types::has_fluid(state)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::blocks::default_state as d;
    use crate::blocks_types::block_by_name;

    #[test]
    fn spot_checks_against_known_vanilla_values() {
        assert_eq!((light_emission(d::TORCH), light_dampening(d::STONE)), (14, 15));
        assert_eq!(light_emission(d::GLOWSTONE), 15);
        assert!(propagates_skylight_down(d::GLASS) && !propagates_skylight_down(d::STONE));
        assert_eq!(hardness(d::STONE), 1.5);
        assert_eq!(hardness(d::BEDROCK), -1.0);
        assert!(requires_correct_tool(d::STONE) && !requires_correct_tool(d::DIRT));
        assert_eq!(collision(d::STONE), &[[0.0, 0.0, 0.0, 1.0, 1.0, 1.0]]);
        assert!(collision(d::AIR).is_empty() && collision(d::TORCH).is_empty());
        let slab = block_by_name("minecraft:oak_slab").unwrap();
        assert_eq!(collision(slab.default), &[[0.0, 0.0, 0.0, 1.0, 0.5, 1.0]]);
        assert!(face_full(slab.default, 0) && !face_full(slab.default, 1));
        assert!(replaceable(d::AIR) && replaceable(d::SHORT_GRASS) && !replaceable(d::STONE));
        assert!(motion_blocking(d::STONE) && motion_blocking(d::WATER) && !motion_blocking(d::AIR));
        assert!(motion_blocking(d::OAK_LEAVES) && !motion_blocking_no_leaves(d::OAK_LEAVES));
        assert!(!motion_blocking(d::TORCH));
    }
}
