//! Chunk loading and generation counters, logged next to the tick statistics: how many chunks
//! the generation threads finished and how busy they were, how long a requested chunk took to
//! come back (request until the tick thread collects it), what loading from disk costs on the
//! tick thread, and what installing a chunk costs.
//!
//! Counters are totals since the server started; the log line carries the totals so a
//! benchmark can take differences between lines.

use std::fmt::Write;
use std::sync::atomic::{AtomicU64, Ordering::Relaxed};
use std::time::Duration;

const BUCKETS: usize = 10_001;

/// Milliseconds histogram with a last bucket for everything slower.
pub(crate) struct Hist {
    buckets: [AtomicU64; BUCKETS],
    sum_us: AtomicU64,
    n: AtomicU64,
}

impl Hist {
    const fn new() -> Self {
        Self { buckets: [const { AtomicU64::new(0) }; BUCKETS], sum_us: AtomicU64::new(0), n: AtomicU64::new(0) }
    }

    pub fn add(&self, d: Duration) {
        let ms = (d.as_millis() as usize).min(BUCKETS - 1);
        self.buckets[ms].fetch_add(1, Relaxed);
        self.sum_us.fetch_add(d.as_micros() as u64, Relaxed);
        self.n.fetch_add(1, Relaxed);
    }

    /// (count, mean ms, p50, p99, max) in milliseconds.
    fn summary(&self) -> (u64, f64, usize, usize, usize) {
        let n = self.n.load(Relaxed);
        if n == 0 {
            return (0, 0.0, 0, 0, 0);
        }
        let at = |q: f64| {
            let want = ((n as f64 * q).ceil() as u64).max(1);
            let mut seen = 0;
            for (ms, b) in self.buckets.iter().enumerate() {
                seen += b.load(Relaxed);
                if seen >= want {
                    return ms;
                }
            }
            BUCKETS - 1
        };
        let max = self.buckets.iter().rposition(|b| b.load(Relaxed) > 0).unwrap_or(0);
        (n, self.sum_us.load(Relaxed) as f64 / n as f64 / 1e3, at(0.5), at(0.99), max)
    }
}

/// Chunks generated by the generation threads.
pub(crate) static GEN_DONE: AtomicU64 = AtomicU64::new(0);
/// Time those threads spent generating, summed over threads (ns).
pub(crate) static GEN_BUSY_NS: AtomicU64 = AtomicU64::new(0);
/// From the request until the tick thread collected the chunk.
pub(crate) static GEN_LATENCY: Hist = Hist::new();
/// Chunks read from disk on the tick thread, and the time that took (ns); the longest read.
pub(crate) static DISK_HITS: AtomicU64 = AtomicU64::new(0);
pub(crate) static DISK_NS: AtomicU64 = AtomicU64::new(0);
pub(crate) static DISK_MAX_NS: AtomicU64 = AtomicU64::new(0);
/// Disk lookups that found nothing (the chunk was then generated) and their time (ns).
pub(crate) static DISK_MISSES: AtomicU64 = AtomicU64::new(0);
pub(crate) static DISK_MISS_NS: AtomicU64 = AtomicU64::new(0);
/// Chunks installed into their region (generated or loaded), the time the tick thread spent
/// doing it (ns), and the longest single install.
pub(crate) static INSTALLED: AtomicU64 = AtomicU64::new(0);
pub(crate) static INSTALL_NS: AtomicU64 = AtomicU64::new(0);
pub(crate) static INSTALL_MAX_NS: AtomicU64 = AtomicU64::new(0);
/// Chunks generated on the tick thread because something needed them at once (joins,
/// teleports, commands), and the time that took (ns).
pub(crate) static SYNC_LOADS: AtomicU64 = AtomicU64::new(0);
pub(crate) static SYNC_NS: AtomicU64 = AtomicU64::new(0);

pub(crate) fn count(counter: &AtomicU64) {
    counter.fetch_add(1, Relaxed);
}

pub(crate) fn add_ns(counter: &AtomicU64, d: Duration) {
    counter.fetch_add(d.as_nanos() as u64, Relaxed);
}

pub(crate) fn max_ns(counter: &AtomicU64, d: Duration) {
    counter.fetch_max(d.as_nanos() as u64, Relaxed);
}

/// One log line with the totals: `key=value` pairs a benchmark parses.
pub(crate) fn line(gen_threads: usize) -> String {
    let (n, mean, p50, p99, max) = GEN_LATENCY.summary();
    let mut s = String::new();
    let ms = |c: &AtomicU64| c.load(Relaxed) as f64 / 1e6;
    let _ = write!(
        s,
        "chunk totals: gen_done={} gen_busy_ms={:.0} gen_threads={gen_threads} gen_latency_n={n} gen_latency_mean_ms={mean:.1} \
         gen_latency_p50_ms={p50} gen_latency_p99_ms={p99} gen_latency_max_ms={max} \
         disk_hits={} disk_ms={:.1} disk_max_ms={:.2} disk_misses={} disk_miss_ms={:.1} \
         installed={} install_ms={:.1} install_max_ms={:.2} sync_loads={} sync_ms={:.1}",
        GEN_DONE.load(Relaxed),
        ms(&GEN_BUSY_NS),
        DISK_HITS.load(Relaxed),
        ms(&DISK_NS),
        ms(&DISK_MAX_NS),
        DISK_MISSES.load(Relaxed),
        ms(&DISK_MISS_NS),
        INSTALLED.load(Relaxed),
        ms(&INSTALL_NS),
        ms(&INSTALL_MAX_NS),
        SYNC_LOADS.load(Relaxed),
        ms(&SYNC_NS),
    );
    s
}
