//! `cargo xtask codegen` turns the vanilla data generator output in `<work>/generated`
//! (plus a little bytecode inspection of the unobfuscated server jar via `javap`) into
//! the Rust tables in `crates/kiln-data/src/gen/`. Only interoperability facts (names,
//! numeric IDs) are emitted; Mojang's data files themselves stay in the work directory.

use crate::bytecode::synchronized_registries;
use crate::read_json;
use anyhow::{Context, Result, bail};
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

pub(crate) struct Input {
    pub(crate) generated: PathBuf,
    pub(crate) server_jar: PathBuf,
}

pub fn run(root: &Path, work: &Path) -> Result<()> {
    let version_file = work.join("server_version.json");
    let version: Value = read_json(&version_file)
        .with_context(|| format!("run `cargo xtask fetch` first ({} missing)", version_file.display()))?;
    // The bundler's versions.list names the jar; snapshot display names differ from their ids.
    let input = Input { generated: work.join("generated"), server_jar: crate::fetch::server_jar(work)? };
    let out = root.join("crates/kiln-data/src/gen");
    fs::create_dir_all(&out)?;

    fs::write(out.join("version.rs"), gen_version(&version)?)?;
    fs::write(out.join("packets.rs"), gen_packets(&input)?)?;
    fs::write(out.join("blocks.rs"), gen_blocks(&input)?)?;
    let registries = gen_registries(&input)?;
    fs::write(out.join("registries.rs"), registries)?;
    fs::write(out.join("entities.rs"), crate::entities::gen_entities(&input)?)?;
    let extra = read_json(&input.generated.join("extra/block_states.json")).context("run `cargo xtask extract` first")?;
    let blocks = read_json(&input.generated.join("reports/blocks.json"))?;
    let state_count = blocks.as_object().context("blocks")?.values().map(|b| b["states"].as_array().map_or(0, Vec::len)).sum();
    let builtin = read_json(&input.generated.join("reports/registries.json"))?;
    let block_entity_types: HashMap<String, u8> = builtin["minecraft:block_entity_type"]["entries"]
        .as_object()
        .context("block_entity_type registry")?
        .iter()
        .map(|(k, v)| (k.clone(), v["protocol_id"].as_u64().unwrap() as u8))
        .collect();
    fs::write(out.join("block_props.bin"), crate::block_props::pack(&extra, state_count, &block_entity_types)?)?;
    let logic = read_json(&input.generated.join("extra/block_logic.json")).context("run `cargo xtask extract` first")?;
    let instruments: Vec<String> = blocks["minecraft:note_block"]["properties"]["instrument"]
        .as_array()
        .context("note block instruments")?
        .iter()
        .map(|v| v.as_str().unwrap_or_default().to_string())
        .collect();
    fs::write(out.join("block_logic.bin"), crate::block_logic::pack(&logic, state_count, &instruments)?)?;
    let classes = read_json(&input.generated.join("extra/block_classes.json")).context("run `cargo xtask extract` first")?;
    fs::write(out.join("block_classes.rs"), crate::block_logic::gen_classes(&classes)?)?;
    let block_items = read_json(&input.generated.join("extra/block_items.json")).context("run `cargo xtask extract` first")?;
    fs::write(out.join("block_items.rs"), crate::block_logic::gen_block_items(&block_items)?)?;
    let rules = read_json(&input.generated.join("extra/game_rules.json")).context("run `cargo xtask extract` first")?;
    fs::write(out.join("game_rules.rs"), gen_game_rules(&rules)?)?;
    println!("codegen: wrote {}", out.display());

    let items = read_json(&input.generated.join("extra/item_components.json")).context("run `cargo xtask extract items` first")?;
    let item_out = root.join("crates/kiln-item/src/gen");
    fs::create_dir_all(&item_out)?;
    crate::items::generate(&items, &item_out)?;
    println!("codegen: wrote {}", item_out.display());
    Ok(())
}

pub(crate) const HEADER: &str = "// @generated by `cargo xtask codegen` from the vanilla data generator. Do not edit.\n\n";

/// Rust constant name for a registry or packet id, as used in `kiln-data`.
pub(crate) fn const_name(id: &str) -> String {
    let path = id.strip_prefix("minecraft:").unwrap_or(id);
    let mut s: String = path
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_uppercase() } else { '_' })
        .collect();
    if s.starts_with(|c: char| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    s
}

/// Game rules in registry order with their default values.
fn gen_game_rules(rules: &Value) -> Result<String> {
    let mut s = String::from(HEADER);
    s.push_str("use crate::GameRuleDefault::{self, Bool, Int};

");
    s.push_str("pub const GAME_RULES: &[(&str, GameRuleDefault)] = &[
");
    for r in rules.as_array().context("game rules")? {
        let name = r["name"].as_str().context("name")?;
        let default = r["default"].as_str().context("default")?;
        let value = match r["type"].as_str() {
            Some("bool") => format!("Bool({default})"),
            Some("int") => format!("Int({default})"),
            other => bail!("game rule {name}: unsupported type {other:?}"),
        };
        writeln!(s, "    ({name:?}, {value}),")?;
    }
    s.push_str("];
");
    Ok(s)
}

fn gen_version(v: &Value) -> Result<String> {
    let mut s = String::from(HEADER);
    writeln!(s, "pub const NAME: &str = {:?};", v["name"].as_str().context("name")?)?;
    writeln!(s, "pub const PROTOCOL: i32 = {};", v["protocol_version"].as_i64().context("protocol")?)?;
    writeln!(s, "pub const WORLD_VERSION: i32 = {};", v["world_version"].as_i64().context("world_version")?)?;
    Ok(s)
}

fn gen_packets(input: &Input) -> Result<String> {
    let packets = read_json(&input.generated.join("reports/packets.json"))?;
    let mut s = String::from(HEADER);
    for (state, dirs) in packets.as_object().context("packets")? {
        writeln!(s, "pub mod {state} {{")?;
        for (dir, list) in dirs.as_object().context("dirs")? {
            writeln!(s, "    pub mod {dir} {{")?;
            let mut rows: Vec<(i64, &str)> = list
                .as_object()
                .context("list")?
                .iter()
                .map(|(k, v)| (v["protocol_id"].as_i64().unwrap(), k.as_str()))
                .collect();
            rows.sort();
            for (id, name) in &rows {
                writeln!(s, "        pub const {}: i32 = {id};", const_name(name))?;
            }
            writeln!(s, "        pub const NAMES: &[&str] = &[")?;
            for (_, name) in &rows {
                writeln!(s, "            {name:?},")?;
            }
            writeln!(s, "        ];\n    }}")?;
        }
        writeln!(s, "}}")?;
    }
    Ok(s)
}

fn gen_blocks(input: &Input) -> Result<String> {
    struct Row {
        first: u64,
        name: String,
        default: u64,
        last: u64,
        props: Vec<(String, Vec<String>)>,
    }
    let blocks = read_json(&input.generated.join("reports/blocks.json"))?;
    let blocks = blocks.as_object().context("blocks")?;
    let mut rows = Vec::new();
    let mut state_count = 0u64;
    for (name, b) in blocks {
        let props: Vec<(String, Vec<String>)> = match b.get("properties").and_then(Value::as_object) {
            Some(p) => p
                .iter()
                .map(|(k, v)| {
                    let vals = v.as_array().unwrap().iter().map(|x| x.as_str().unwrap().to_string()).collect();
                    (k.clone(), vals)
                })
                .collect(),
            None => Vec::new(),
        };
        let states = b["states"].as_array().context("states")?;
        let first = states.iter().map(|st| st["id"].as_u64().unwrap()).min().context("states")?;
        let mut default = None;
        let mut last = 0;
        for st in states {
            let id = st["id"].as_u64().context("id")?;
            last = last.max(id);
            if st.get("default").and_then(Value::as_bool) == Some(true) {
                default = Some(id);
            }
            // State ids enumerate property values with the last property varying fastest.
            let mut offset = 0u64;
            for (pname, vals) in &props {
                let v = st["properties"][pname].as_str().context("property value")?;
                let idx = vals.iter().position(|x| x == v).context("unknown property value")? as u64;
                offset = offset * vals.len() as u64 + idx;
            }
            if first + offset != id {
                bail!("{name}: state {id} does not follow the property order");
            }
        }
        state_count = state_count.max(last + 1);
        rows.push(Row { first, name: name.clone(), default: default.context("default state")?, last, props });
    }
    rows.sort_by_key(|r| r.first);
    if state_count > u16::MAX as u64 {
        bail!("{state_count} block states no longer fit in u16");
    }
    let mut s = String::from(HEADER);
    writeln!(s, "use crate::blocks_types::{{BlockInfo, Property}};\n")?;
    writeln!(s, "/// Number of block states (the global palette size).")?;
    writeln!(s, "pub const STATE_COUNT: u32 = {state_count};")?;
    writeln!(s, "\n/// Default block state of each block.")?;
    writeln!(s, "pub mod default_state {{")?;
    for r in &rows {
        writeln!(s, "    pub const {}: u16 = {};", const_name(&r.name), r.default)?;
    }
    writeln!(s, "}}\n\n/// Blocks in state-id order.")?;
    writeln!(s, "pub static BLOCKS: &[BlockInfo] = &[")?;
    for r in &rows {
        write!(
            s,
            "    BlockInfo {{ name: {:?}, first: {}, default: {}, last: {}, properties: &[",
            r.name, r.first, r.default, r.last
        )?;
        for (pname, vals) in &r.props {
            write!(s, "Property {{ name: {pname:?}, values: &{vals:?} }}, ")?;
        }
        writeln!(s, "] }},")?;
    }
    writeln!(s, "];")?;
    Ok(s)
}

/// Lists `data/minecraft/<dir>/**/*.json` as sorted entry ids.
pub(crate) fn datapack_entries(data: &Path, dir: &str) -> Result<Vec<String>> {
    let base = data.join("minecraft").join(dir);
    let mut out = Vec::new();
    walk(&base, &base, &mut out)?;
    out.sort();
    Ok(out.into_iter().map(|p| format!("minecraft:{p}")).collect())
}

/// Collects the `.json` files under `dir` as `/`-separated paths relative to `base`, without extension.
pub(crate) fn walk(base: &Path, dir: &Path, out: &mut Vec<String>) -> Result<()> {
    for e in fs::read_dir(dir).with_context(|| format!("reading {}", dir.display()))? {
        let e = e?;
        let p = e.path();
        if e.file_type()?.is_dir() {
            walk(base, &p, out)?;
        } else if p.extension().is_some_and(|x| x == "json") {
            let rel = p.strip_prefix(base)?.with_extension("");
            out.push(rel.to_string_lossy().replace('\\', "/"));
        }
    }
    Ok(())
}

fn gen_registries(input: &Input) -> Result<String> {
    let data = input.generated.join("data");
    let synced = synchronized_registries(&input.server_jar)?;

    // Registry name -> entry name -> numeric id.
    let mut ids: BTreeMap<String, HashMap<String, i32>> = BTreeMap::new();
    let mut s = String::from(HEADER);

    writeln!(s, "/// Synchronized (data-driven) registries in vanilla send order; entries are")?;
    writeln!(s, "/// sorted by name and their index is the network id.")?;
    writeln!(s, "pub const SYNCHRONIZED: &[(&str, &[&str])] = &[")?;
    for reg in &synced {
        let dir = reg.strip_prefix("minecraft:").unwrap();
        let entries = datapack_entries(&data, dir)?;
        if entries.is_empty() {
            bail!("synchronized registry {reg} has no entries");
        }
        writeln!(s, "    ({reg:?}, &[")?;
        for e in &entries {
            writeln!(s, "        {e:?},")?;
        }
        writeln!(s, "    ]),")?;
        ids.insert(reg.clone(), entries.into_iter().enumerate().map(|(i, e)| (e, i as i32)).collect());
    }
    writeln!(s, "];\n")?;

    let builtin = read_json(&input.generated.join("reports/registries.json"))?;
    writeln!(s, "/// Built-in (static) registries: entries indexed by protocol id.")?;
    writeln!(s, "pub const BUILTIN: &[(&str, &[&str])] = &[")?;
    for (reg, body) in builtin.as_object().context("registries")? {
        let entries = body["entries"].as_object().context("entries")?;
        let map: HashMap<String, i32> = entries
            .iter()
            .map(|(k, v)| (k.clone(), v["protocol_id"].as_i64().unwrap() as i32))
            .collect();
        let mut by_id: Vec<(&i32, &String)> = map.iter().map(|(k, v)| (v, k)).collect();
        by_id.sort();
        for (i, (id, name)) in by_id.iter().enumerate() {
            if **id != i as i32 {
                bail!("{reg}: protocol ids are not dense at {name}");
            }
        }
        writeln!(s, "    ({reg:?}, &[")?;
        for (_, name) in &by_id {
            writeln!(s, "        {name:?},")?;
        }
        writeln!(s, "    ]),")?;
        ids.insert(reg.clone(), map);
    }
    writeln!(s, "];
")?;

    // Tags for every registry the client knows (built-in + synchronized) that has a tag folder.
    let tag_root = data.join("minecraft/tags");
    writeln!(s, "/// Tags for Update Tags: (registry, [(tag, entry ids)]).")?;
    writeln!(s, "pub const TAGS: &[(&str, &[(&str, &[i32])])] = &[")?;
    let mut tag_count = 0;
    for (reg, entry_ids) in &ids {
        let dir = tag_root.join(reg.strip_prefix("minecraft:").unwrap());
        if !dir.is_dir() {
            continue;
        }
        let mut raw = BTreeMap::new();
        let mut names = Vec::new();
        walk(&dir, &dir, &mut names)?;
        for n in names {
            let v = read_json(&dir.join(format!("{n}.json")))?;
            raw.insert(format!("minecraft:{n}"), v);
        }
        let mut resolved: BTreeMap<String, BTreeSet<i32>> = BTreeMap::new();
        for tag in raw.keys() {
            let mut out = BTreeSet::new();
            resolve_tag(tag, &raw, entry_ids, &mut out, &mut Vec::new())?;
            resolved.insert(tag.clone(), out);
        }
        writeln!(s, "    ({reg:?}, &[")?;
        for (tag, set) in &resolved {
            let list: Vec<String> = set.iter().map(i32::to_string).collect();
            writeln!(s, "        ({tag:?}, &[{}]),", list.join(", "))?;
            tag_count += 1;
        }
        writeln!(s, "    ]),")?;
    }
    writeln!(s, "];")?;
    println!("codegen: {} synchronized registries, {tag_count} tags", synced.len());
    Ok(s)
}

fn resolve_tag(
    tag: &str,
    raw: &BTreeMap<String, Value>,
    ids: &HashMap<String, i32>,
    out: &mut BTreeSet<i32>,
    stack: &mut Vec<String>,
) -> Result<()> {
    if stack.iter().any(|t| t == tag) {
        bail!("tag cycle through {tag}");
    }
    let Some(def) = raw.get(tag) else { bail!("unknown tag #{tag}") };
    stack.push(tag.to_string());
    for v in def["values"].as_array().context("values")? {
        let (id, required) = match v {
            Value::String(s) => (s.as_str(), true),
            Value::Object(o) => (
                o["id"].as_str().context("id")?,
                o.get("required").and_then(Value::as_bool).unwrap_or(true),
            ),
            _ => bail!("bad tag value in {tag}"),
        };
        if let Some(inner) = id.strip_prefix('#') {
            if raw.contains_key(inner) || required {
                resolve_tag(inner, raw, ids, out, stack)?;
            }
        } else if let Some(&n) = ids.get(id) {
            out.insert(n);
        } else if required {
            bail!("tag {tag} references unknown entry {id}");
        }
    }
    stack.pop();
    Ok(())
}
