//! `cargo xtask codegen` turns the vanilla data generator output in `<work>/generated`
//! (plus a little bytecode inspection of the unobfuscated server jar via `javap`) into
//! the Rust tables in `crates/kiln-data/src/gen/`. Only interoperability facts (names,
//! numeric IDs) are emitted; Mojang's data files themselves stay in the work directory.

use crate::bytecode::synchronized_registries;
use crate::read_json;
use anyhow::{Context, Result, bail};
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

struct Input {
    generated: PathBuf,
    server_jar: PathBuf,
}

pub fn run(root: &Path, work: &Path) -> Result<()> {
    let version_file = work.join("server_version.json");
    let version: Value = read_json(&version_file)
        .with_context(|| format!("run `cargo xtask fetch` first ({} missing)", version_file.display()))?;
    // The bundler's versions.list names the jar; snapshot display names differ from their ids.
    let input = Input { generated: work.join("generated"), server_jar: crate::fetch::server_jar(work)? };
    let out = root.join("crates/kiln-data/src/gen");
    fs::create_dir_all(&out)?;

    fs::write(out.join("version.rs"), gen_version(&version)?)?;
    fs::write(out.join("packets.rs"), gen_packets(&input)?)?;
    fs::write(out.join("blocks.rs"), gen_blocks(&input)?)?;
    let registries = gen_registries(&input)?;
    fs::write(out.join("registries.rs"), registries)?;
    println!("codegen: wrote {}", out.display());
    Ok(())
}

const HEADER: &str = "// @generated by `cargo xtask codegen` from the vanilla data generator. Do not edit.\n\n";

/// Rust constant name for a registry or packet id, as used in `kiln-data`.
pub(crate) fn const_name(id: &str) -> String {
    let path = id.strip_prefix("minecraft:").unwrap_or(id);
    let mut s: String = path
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_uppercase() } else { '_' })
        .collect();
    if s.starts_with(|c: char| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    s
}

fn gen_version(v: &Value) -> Result<String> {
    let mut s = String::from(HEADER);
    writeln!(s, "pub const NAME: &str = {:?};", v["name"].as_str().context("name")?)?;
    writeln!(s, "pub const PROTOCOL: i32 = {};", v["protocol_version"].as_i64().context("protocol")?)?;
    writeln!(s, "pub const WORLD_VERSION: i32 = {};", v["world_version"].as_i64().context("world_version")?)?;
    Ok(s)
}

fn gen_packets(input: &Input) -> Result<String> {
    let packets = read_json(&input.generated.join("reports/packets.json"))?;
    let mut s = String::from(HEADER);
    for (state, dirs) in packets.as_object().context("packets")? {
        writeln!(s, "pub mod {state} {{")?;
        for (dir, list) in dirs.as_object().context("dirs")? {
            writeln!(s, "    pub mod {dir} {{")?;
            let mut rows: Vec<(i64, &str)> = list
                .as_object()
                .context("list")?
                .iter()
                .map(|(k, v)| (v["protocol_id"].as_i64().unwrap(), k.as_str()))
                .collect();
            rows.sort();
            for (id, name) in &rows {
                writeln!(s, "        pub const {}: i32 = {id};", const_name(name))?;
            }
            writeln!(s, "        pub const NAMES: &[&str] = &[")?;
            for (_, name) in &rows {
                writeln!(s, "            {name:?},")?;
            }
            writeln!(s, "        ];\n    }}")?;
        }
        writeln!(s, "}}")?;
    }
    Ok(s)
}

fn gen_blocks(input: &Input) -> Result<String> {
    let blocks = read_json(&input.generated.join("reports/blocks.json"))?;
    let blocks = blocks.as_object().context("blocks")?;
    let mut rows = Vec::new();
    let mut state_count = 0u64;
    for (name, b) in blocks {
        let states = b["states"].as_array().context("states")?;
        let mut min = u64::MAX;
        let mut max = 0;
        let mut default = None;
        for st in states {
            let id = st["id"].as_u64().context("id")?;
            min = min.min(id);
            max = max.max(id);
            if st.get("default").and_then(Value::as_bool) == Some(true) {
                default = Some(id);
            }
        }
        state_count = state_count.max(max + 1);
        rows.push((min, name.clone(), default.context("default state")?, max));
    }
    rows.sort();
    if state_count > u16::MAX as u64 {
        bail!("{state_count} block states no longer fit in u16");
    }
    let mut s = String::from(HEADER);
    writeln!(s, "/// Number of block states (the global palette size).")?;
    writeln!(s, "pub const STATE_COUNT: u32 = {state_count};")?;
    writeln!(s, "\n/// Default block state of each block.")?;
    writeln!(s, "pub mod default_state {{")?;
    for (_, name, default, _) in &rows {
        writeln!(s, "    pub const {}: u16 = {default};", const_name(name))?;
    }
    writeln!(s, "}}\n\n/// (name, first state, default state, last state) in state-id order.")?;
    writeln!(s, "pub const BLOCKS: &[(&str, u16, u16, u16)] = &[")?;
    for (min, name, default, max) in &rows {
        writeln!(s, "    ({name:?}, {min}, {default}, {max}),")?;
    }
    writeln!(s, "];")?;
    Ok(s)
}

/// Lists `data/minecraft/<dir>/**/*.json` as sorted entry ids.
pub(crate) fn datapack_entries(data: &Path, dir: &str) -> Result<Vec<String>> {
    let base = data.join("minecraft").join(dir);
    let mut out = Vec::new();
    walk(&base, &base, &mut out)?;
    out.sort();
    Ok(out.into_iter().map(|p| format!("minecraft:{p}")).collect())
}

/// Collects the `.json` files under `dir` as `/`-separated paths relative to `base`, without extension.
pub(crate) fn walk(base: &Path, dir: &Path, out: &mut Vec<String>) -> Result<()> {
    for e in fs::read_dir(dir).with_context(|| format!("reading {}", dir.display()))? {
        let e = e?;
        let p = e.path();
        if e.file_type()?.is_dir() {
            walk(base, &p, out)?;
        } else if p.extension().is_some_and(|x| x == "json") {
            let rel = p.strip_prefix(base)?.with_extension("");
            out.push(rel.to_string_lossy().replace('\\', "/"));
        }
    }
    Ok(())
}

fn gen_registries(input: &Input) -> Result<String> {
    let data = input.generated.join("data");
    let synced = synchronized_registries(&input.server_jar)?;

    // Registry name -> entry name -> numeric id.
    let mut ids: BTreeMap<String, HashMap<String, i32>> = BTreeMap::new();
    let mut s = String::from(HEADER);

    writeln!(s, "/// Synchronized (data-driven) registries in vanilla send order; entries are")?;
    writeln!(s, "/// sorted by name and their index is the network id.")?;
    writeln!(s, "pub const SYNCHRONIZED: &[(&str, &[&str])] = &[")?;
    for reg in &synced {
        let dir = reg.strip_prefix("minecraft:").unwrap();
        let entries = datapack_entries(&data, dir)?;
        if entries.is_empty() {
            bail!("synchronized registry {reg} has no entries");
        }
        writeln!(s, "    ({reg:?}, &[")?;
        for e in &entries {
            writeln!(s, "        {e:?},")?;
        }
        writeln!(s, "    ]),")?;
        ids.insert(reg.clone(), entries.into_iter().enumerate().map(|(i, e)| (e, i as i32)).collect());
    }
    writeln!(s, "];\n")?;

    let builtin = read_json(&input.generated.join("reports/registries.json"))?;
    writeln!(s, "/// Built-in (static) registries: entries indexed by protocol id.")?;
    writeln!(s, "pub const BUILTIN: &[(&str, &[&str])] = &[")?;
    for (reg, body) in builtin.as_object().context("registries")? {
        let entries = body["entries"].as_object().context("entries")?;
        let map: HashMap<String, i32> = entries
            .iter()
            .map(|(k, v)| (k.clone(), v["protocol_id"].as_i64().unwrap() as i32))
            .collect();
        let mut by_id: Vec<(&i32, &String)> = map.iter().map(|(k, v)| (v, k)).collect();
        by_id.sort();
        for (i, (id, name)) in by_id.iter().enumerate() {
            if **id != i as i32 {
                bail!("{reg}: protocol ids are not dense at {name}");
            }
        }
        writeln!(s, "    ({reg:?}, &[")?;
        for (_, name) in &by_id {
            writeln!(s, "        {name:?},")?;
        }
        writeln!(s, "    ]),")?;
        ids.insert(reg.clone(), map);
    }
    writeln!(s, "];
")?;

    // Tags for every registry the client knows (built-in + synchronized) that has a tag folder.
    let tag_root = data.join("minecraft/tags");
    writeln!(s, "/// Tags for Update Tags: (registry, [(tag, entry ids)]).")?;
    writeln!(s, "pub const TAGS: &[(&str, &[(&str, &[i32])])] = &[")?;
    let mut tag_count = 0;
    for (reg, entry_ids) in &ids {
        let dir = tag_root.join(reg.strip_prefix("minecraft:").unwrap());
        if !dir.is_dir() {
            continue;
        }
        let mut raw = BTreeMap::new();
        let mut names = Vec::new();
        walk(&dir, &dir, &mut names)?;
        for n in names {
            let v = read_json(&dir.join(format!("{n}.json")))?;
            raw.insert(format!("minecraft:{n}"), v);
        }
        let mut resolved: BTreeMap<String, BTreeSet<i32>> = BTreeMap::new();
        for tag in raw.keys() {
            let mut out = BTreeSet::new();
            resolve_tag(tag, &raw, entry_ids, &mut out, &mut Vec::new())?;
            resolved.insert(tag.clone(), out);
        }
        writeln!(s, "    ({reg:?}, &[")?;
        for (tag, set) in &resolved {
            let list: Vec<String> = set.iter().map(i32::to_string).collect();
            writeln!(s, "        ({tag:?}, &[{}]),", list.join(", "))?;
            tag_count += 1;
        }
        writeln!(s, "    ]),")?;
    }
    writeln!(s, "];")?;
    println!("codegen: {} synchronized registries, {tag_count} tags", synced.len());
    Ok(s)
}

fn resolve_tag(
    tag: &str,
    raw: &BTreeMap<String, Value>,
    ids: &HashMap<String, i32>,
    out: &mut BTreeSet<i32>,
    stack: &mut Vec<String>,
) -> Result<()> {
    if stack.iter().any(|t| t == tag) {
        bail!("tag cycle through {tag}");
    }
    let Some(def) = raw.get(tag) else { bail!("unknown tag #{tag}") };
    stack.push(tag.to_string());
    for v in def["values"].as_array().context("values")? {
        let (id, required) = match v {
            Value::String(s) => (s.as_str(), true),
            Value::Object(o) => (
                o["id"].as_str().context("id")?,
                o.get("required").and_then(Value::as_bool).unwrap_or(true),
            ),
            _ => bail!("bad tag value in {tag}"),
        };
        if let Some(inner) = id.strip_prefix('#') {
            if raw.contains_key(inner) || required {
                resolve_tag(inner, raw, ids, out, stack)?;
            }
        } else if let Some(&n) = ids.get(id) {
            out.insert(n);
        } else if required {
            bail!("tag {tag} references unknown entry {id}");
        }
    }
    stack.pop();
    Ok(())
}
