//! `cargo xtask fetch`: rebuilds a work directory from Mojang's servers.
//!
//! Layout, relative to the work directory:
//! - `manifest.json`, `version.json`: launcher metadata; the version json's SHA-1 is checked
//!   against the manifest
//! - `server.jar`, `server_url.txt`: the bundler jar (SHA-1 checked) and where it came from
//! - `versions/<id>/server-<id>.jar`, `libraries/`: unpacked by the bundler when the data
//!   generator runs; the unobfuscated server jar is what `javap` reads
//! - `generated/`, `datagen.log`, `logs/`: data generator output (`--reports --server`) and
//!   its console output
//! - `server_version.json`: `version.json` from inside the jar, written last so that its
//!   presence marks a complete fetch
//! - `spec/*.wiki`: minecraft.wiki protocol pages (only when fetching the latest release)

use crate::Args;
use crate::http::{self, Http};
use crate::zip::Zip;
use anyhow::{Context, Result, bail, ensure};
use serde_json::Value;
use std::fs::{self, File};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::Instant;

const MANIFEST_URL: &str = "https://piston-meta.mojang.com/mc/game/version_manifest_v2.json";

/// minecraft.wiki pages about the latest release's protocol: (file in `spec/`, page).
const SPEC_PAGES: &[(&str, &str)] = &[
    ("packets.wiki", "Java_Edition_protocol/Packets"),
    ("data_types.wiki", "Java_Edition_protocol/Data_types"),
    ("chunk_format.wiki", "Java_Edition_protocol/Chunk_format"),
    ("registries.wiki", "Java_Edition_protocol/Registries"),
];

pub enum Want {
    LatestRelease,
    LatestSnapshot,
    Id(String),
}

pub struct Options {
    pub want: Want,
    /// Also download the minecraft.wiki protocol pages.
    pub spec: bool,
    /// Rerun the data generator even if its output is up to date.
    pub force: bool,
}

pub fn run(work: &Path, mut args: Args) -> Result<()> {
    let id = args.value("--version")?;
    let snapshot = args.flag("--snapshot");
    let spec = !args.flag("--no-spec");
    let force = args.flag("--force");
    args.finish()?;
    let want = match (id, snapshot) {
        (Some(_), true) => bail!("--version and --snapshot are mutually exclusive"),
        (Some(id), false) => Want::Id(id),
        (None, true) => Want::LatestSnapshot,
        (None, false) => Want::LatestRelease,
    };
    fetch(&Http::new(), work, &Options { want, spec, force })?;
    Ok(())
}

fn str_field<'a>(v: &'a Value, key: &str) -> Result<&'a str> {
    v[key].as_str().with_context(|| format!("missing string field {key:?}"))
}

/// Id of the latest snapshot in Mojang's version manifest.
pub fn latest_snapshot(http: &Http) -> Result<String> {
    let manifest: Value = serde_json::from_slice(&http.get(MANIFEST_URL)?).context("parsing the version manifest")?;
    Ok(str_field(&manifest["latest"], "snapshot")?.to_string())
}

/// Fetches into `work` and returns the unobfuscated server jar unpacked by the bundler.
pub fn fetch(http: &Http, work: &Path, opts: &Options) -> Result<PathBuf> {
    fs::create_dir_all(work).with_context(|| format!("creating {}", work.display()))?;
    println!("fetch: work directory {}", work.display());

    let manifest_bytes = http.get(MANIFEST_URL)?;
    let manifest: Value = serde_json::from_slice(&manifest_bytes).context("parsing the version manifest")?;
    fs::write(work.join("manifest.json"), &manifest_bytes)?;
    let id = match &opts.want {
        Want::LatestRelease => str_field(&manifest["latest"], "release")?,
        Want::LatestSnapshot => str_field(&manifest["latest"], "snapshot")?,
        Want::Id(id) => id.as_str(),
    };
    let entry = manifest["versions"]
        .as_array()
        .context("manifest versions")?
        .iter()
        .find(|v| v["id"] == id)
        .with_context(|| format!("version {id} is not in Mojang's version manifest"))?;

    let version_bytes = http.get(str_field(entry, "url")?)?;
    http::verify_sha1(&format!("{id}.json"), &version_bytes, str_field(entry, "sha1")?)?;
    fs::write(work.join("version.json"), &version_bytes)?;
    let version: Value = serde_json::from_slice(&version_bytes)?;
    let server = &version["downloads"]["server"];
    let url = str_field(server, "url").with_context(|| format!("{id} has no server download"))?;
    let sha1 = str_field(server, "sha1")?;
    check_java(id, version["javaVersion"]["majorVersion"].as_u64())?;

    let jar = work.join("server.jar");
    let complete = work.join("server_version.json");
    let cached = jar.is_file() && http::sha1_file(&jar)? == sha1;
    if cached {
        println!("fetch: server.jar for {id} already present (SHA-1 {sha1})");
    } else {
        // Everything unpacked from or generated by another server jar is stale now.
        remove_file(&complete)?;
        remove_dir(&work.join("versions"))?;
        remove_dir(&work.join("libraries"))?;
        let mb = server["size"].as_f64().unwrap_or(0.0) / 1e6;
        println!("fetch: downloading the {id} server.jar ({mb:.1} MB)");
        http.download(url, &jar, sha1)?;
        println!("fetch: SHA-1 {sha1} verified");
    }
    fs::write(work.join("server_url.txt"), format!("{url} {sha1}\n"))?;

    let bundle = Zip::open(&jar)?;
    let jar_version = bundle.read("version.json")?;
    let server_jar = work.join("versions").join(bundled_version_path(&bundle)?);
    let up_to_date = !opts.force
        && cached
        && fs::read(&complete).is_ok_and(|b| b == jar_version)
        && work.join("generated/reports/packets.json").is_file()
        && server_jar.is_file();
    if up_to_date {
        println!("fetch: generated data is up to date (--force reruns the data generator)");
    } else {
        remove_file(&complete)?;
        run_data_generator(work)?;
        ensure!(server_jar.is_file(), "the bundler did not unpack {}", server_jar.display());
        fs::write(&complete, &jar_version)?;
    }

    if opts.spec {
        fetch_spec(http, work, id, &manifest)?;
    }
    let v: Value = serde_json::from_slice(&jar_version).context("parsing version.json from server.jar")?;
    println!(
        "fetch: {} (protocol {}, world version {}) ready in {}",
        v["name"].as_str().unwrap_or(id),
        v["protocol_version"],
        v["world_version"],
        work.display()
    );
    Ok(server_jar)
}

/// The unobfuscated server jar of a fetched work directory.
pub fn server_jar(work: &Path) -> Result<PathBuf> {
    let bundle = Zip::open(&work.join("server.jar"))?;
    Ok(work.join("versions").join(bundled_version_path(&bundle)?))
}

/// Path of the server jar under `versions/`, from the bundler's `META-INF/versions.list`
/// (`<sha256>\t<id>\t<path>` lines).
fn bundled_version_path(bundle: &Zip) -> Result<String> {
    let list = String::from_utf8(bundle.read("META-INF/versions.list")?)?;
    let line = list.lines().find(|l| !l.trim().is_empty()).context("empty versions.list")?;
    let path = line.split('\t').nth(2).context("malformed versions.list")?;
    Ok(path.trim().to_string())
}

/// Runs the vanilla data generator into `generated.tmp` and swaps it in on success, so an
/// interrupted run never leaves a half-written `generated/`.
fn run_data_generator(work: &Path) -> Result<()> {
    let tmp = work.join("generated.tmp");
    remove_dir(&tmp)?;
    let log_path = work.join("datagen.log");
    let log = File::create(&log_path)?;
    println!("fetch: running the data generator (--reports --server)");
    let start = Instant::now();
    let status = Command::new("java")
        .current_dir(work)
        .args(["-DbundlerMainClass=net.minecraft.data.Main", "-jar", "server.jar"])
        .args(["--reports", "--server", "--output", "generated.tmp"])
        .stdin(Stdio::null())
        .stdout(log.try_clone()?)
        .stderr(log)
        .status()
        .context("running java (a JDK must be on PATH)")?;
    if !status.success() {
        bail!("the data generator failed ({status}); see {}", log_path.display());
    }
    ensure!(
        tmp.join("reports/packets.json").is_file(),
        "the data generator wrote no reports/packets.json; see {}",
        log_path.display()
    );
    let out = work.join("generated");
    remove_dir(&out)?;
    fs::rename(&tmp, &out).with_context(|| format!("moving {} into place", tmp.display()))?;
    println!("fetch: data generator finished in {:.1} s", start.elapsed().as_secs_f64());
    Ok(())
}

fn check_java(id: &str, required: Option<u64>) -> Result<()> {
    let out = Command::new("java").arg("-version").output().context("running java (a JDK must be on PATH)")?;
    let text = String::from_utf8_lossy(&out.stderr);
    match (required, java_major(&text)) {
        (Some(need), Some(have)) if have < need => bail!("{id} needs Java {need}, but `java` on PATH is Java {have}"),
        (_, None) => eprintln!("fetch: warning: could not parse `java -version`: {}", text.trim()),
        _ => {}
    }
    Ok(())
}

/// Major version from `java -version` output (`"25.0.3"` -> 25, `"1.8.0_392"` -> 8).
fn java_major(output: &str) -> Option<u64> {
    let start = output.find('"')? + 1;
    let version = &output[start..start + output[start..].find('"')?];
    let mut parts = version.split(['.', '-', '+', '_']);
    match parts.next()?.parse().ok()? {
        1 => parts.next()?.parse().ok(),
        n => Some(n),
    }
}

fn fetch_spec(http: &Http, work: &Path, id: &str, manifest: &Value) -> Result<()> {
    if manifest["latest"]["release"] != id {
        println!("fetch: skipping the minecraft.wiki pages (they describe the latest release, not {id})");
        return Ok(());
    }
    let dir = work.join("spec");
    fs::create_dir_all(&dir)?;
    for (file, page) in SPEC_PAGES {
        // The wiki is a convenience copy; the jar stays the authority, so failures only warn.
        match http.get(&format!("https://minecraft.wiki/w/{page}?action=raw")) {
            Ok(text) => fs::write(dir.join(file), text)?,
            Err(e) => eprintln!("fetch: warning: minecraft.wiki {page}: {e:#}"),
        }
    }
    println!("fetch: minecraft.wiki protocol pages saved to {}", dir.display());
    Ok(())
}

fn remove_file(path: &Path) -> Result<()> {
    match fs::remove_file(path) {
        Err(e) if e.kind() != std::io::ErrorKind::NotFound => {
            Err(e).with_context(|| format!("removing {}", path.display()))
        }
        _ => Ok(()),
    }
}

fn remove_dir(path: &Path) -> Result<()> {
    match fs::remove_dir_all(path) {
        Err(e) if e.kind() != std::io::ErrorKind::NotFound => {
            Err(e).with_context(|| format!("removing {}", path.display()))
        }
        _ => Ok(()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_java_versions() {
        assert_eq!(java_major("openjdk version \"25.0.3\" 2026-04-21 LTS\nOpenJDK Runtime"), Some(25));
        assert_eq!(java_major("java version \"1.8.0_392\""), Some(8));
        assert_eq!(java_major("openjdk version \"26-ea\" 2026-09-16"), Some(26));
        assert_eq!(java_major("no version here"), None);
    }
}
