//! `cargo xtask snapshot-report [<version>]`: what a new drop changes for Kiln.
//!
//! Fetches the version into `<work>/snapshots/<version>`, compares it with the work directory's
//! data and writes `<work>/reports/<version>.md`: version constants, packets, packet class
//! fingerprints, registries, blocks and tags, plus what that means for Kiln.

use crate::bytecode::{self, synchronized_registries};
use crate::codegen::{datapack_entries, walk};
use crate::completeness::{self, Classification, Packet, Status};
use crate::fetch::{self, Options, Want};
use crate::http::Http;
use crate::zip::Zip;
use crate::{Args, read_json};
use anyhow::{Context, Result, ensure};
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
use std::fmt::{Display, Write as _};
use std::fs;
use std::path::{Path, PathBuf};

/// Classes outside the packet list whose changes matter to Kiln's encoders and storage.
const WATCHED: &[(&str, &str)] = &[
    ("net.minecraft.network.codec.ByteBufCodecs", "primitive stream codecs"),
    ("net.minecraft.network.FriendlyByteBuf", "buffer helpers (VarInt, strings, positions)"),
    ("net.minecraft.network.chat.ComponentSerialization", "text components"),
    ("net.minecraft.world.item.ItemStack", "item stack codecs"),
    ("net.minecraft.network.protocol.game.CommonPlayerSpawnInfo", "spawn info in login and respawn"),
    ("net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData", "chunk packet body"),
    ("net.minecraft.network.protocol.game.ClientboundLightUpdatePacketData", "light data"),
    ("net.minecraft.world.level.chunk.LevelChunkSection", "chunk section encoding"),
    ("net.minecraft.world.level.chunk.PalettedContainer", "paletted containers"),
    ("net.minecraft.world.level.chunk.Strategy", "palette strategies and container sizes"),
    ("net.minecraft.world.level.chunk.storage.SerializableChunkData", "chunk NBT (Anvil)"),
    ("net.minecraft.world.level.chunk.status.ChunkPyramid", "chunk generation steps"),
    ("net.minecraft.world.level.levelgen.NoiseGeneratorSettings", "noise settings (worldgen)"),
    ("net.minecraft.resources.RegistryDataLoader", "registry loading and sync order"),
];

pub fn run(root: &Path, work: &Path, mut args: Args) -> Result<()> {
    let version = args.positional();
    args.finish()?;
    ensure!(
        work.join("server_version.json").is_file(),
        "{} has no complete fetch; run `cargo xtask fetch` first",
        work.display()
    );
    let base = DataSet::load(work, fetch::server_jar(work)?)?;

    let http = Http::new();
    let id = match version {
        Some(v) => v,
        None => fetch::latest_snapshot(&http)?,
    };
    ensure!(!id.is_empty() && !id.contains(['/', '\\']) && !id.starts_with('.'), "invalid version id {id:?}");
    let dir = work.join("snapshots").join(&id);
    let jar = fetch::fetch(&http, &dir, &Options { want: Want::Id(id.clone()), spec: false, force: false })?;
    let new = DataSet::load(&dir, jar)?;
    let classification = completeness::load(root)?;

    println!("snapshot-report: comparing {} with {}", new.name, base.name);
    let show = |p: &Path| p.strip_prefix(root).unwrap_or(p).display().to_string().replace('\\', "/");
    let origin = format!(
        "Generated by `cargo xtask snapshot-report {id}` from the data generator output and server bytecode of \
         both versions (base: `{}`, new: `{}`).",
        show(work),
        show(&dir)
    );
    let (md, glance) = render(&base, &new, &classification, &origin)?;
    let out = work.join("reports").join(format!("{id}.md"));
    fs::create_dir_all(out.parent().unwrap())?;
    fs::write(&out, md)?;
    for line in glance {
        println!("  - {line}");
    }
    println!("snapshot-report: wrote {}", out.display());
    Ok(())
}

struct Block {
    first: u64,
    states: u64,
    properties: Value,
}

/// The facts of one fetched version that the report compares.
struct DataSet {
    name: String,
    version: Value,
    jar: PathBuf,
    packets: Vec<Packet>,
    /// Synchronized registries in send order.
    synced: Vec<String>,
    synced_entries: BTreeMap<String, Vec<String>>,
    /// Built-in registries: entries in protocol id order.
    builtin: BTreeMap<String, Vec<String>>,
    blocks: BTreeMap<String, Block>,
    /// Registry -> tag -> unresolved `values`.
    tags: BTreeMap<String, BTreeMap<String, Value>>,
}

fn strip(id: &str) -> &str {
    id.strip_prefix("minecraft:").unwrap_or(id)
}

impl DataSet {
    fn load(dir: &Path, jar: PathBuf) -> Result<Self> {
        let version = read_json(&dir.join("server_version.json"))?;
        let name = version["name"].as_str().context("version name")?.to_string();
        let reports = dir.join("generated/reports");
        let data = dir.join("generated/data");
        let packets = completeness::packets(&read_json(&reports.join("packets.json"))?)?;

        let synced = synchronized_registries(&jar)?;
        let mut synced_entries = BTreeMap::new();
        for reg in &synced {
            let exists = data.join("minecraft").join(strip(reg)).is_dir();
            let entries = if exists { datapack_entries(&data, strip(reg))? } else { Vec::new() };
            synced_entries.insert(reg.clone(), entries);
        }

        let mut builtin = BTreeMap::new();
        for (reg, body) in read_json(&reports.join("registries.json"))?.as_object().context("registries.json")? {
            let mut entries: Vec<(i64, String)> = body["entries"]
                .as_object()
                .context("registry entries")?
                .iter()
                .map(|(k, v)| (v["protocol_id"].as_i64().unwrap_or(-1), k.clone()))
                .collect();
            entries.sort();
            builtin.insert(reg.clone(), entries.into_iter().map(|(_, k)| k).collect());
        }

        let mut blocks = BTreeMap::new();
        for (block, b) in read_json(&reports.join("blocks.json"))?.as_object().context("blocks.json")? {
            let ids: Vec<u64> =
                b["states"].as_array().context("block states")?.iter().filter_map(|s| s["id"].as_u64()).collect();
            let first = ids.iter().min().copied().unwrap_or(0);
            blocks
                .insert(block.clone(), Block { first, states: ids.len() as u64, properties: b["properties"].clone() });
        }

        // Tag files live at tags/<registry path>/<tag path>.json, and registry paths may contain '/'.
        let mut registries: HashSet<String> = builtin.keys().chain(&synced).map(|r| strip(r).to_string()).collect();
        if let Ok(dp) = read_json(&reports.join("datapack.json")) {
            for group in ["registries", "others"] {
                if let Some(m) = dp[group].as_object() {
                    registries.extend(m.keys().map(|k| strip(k).to_string()));
                }
            }
        }
        let tag_root = data.join("minecraft/tags");
        let mut files = Vec::new();
        if tag_root.is_dir() {
            walk(&tag_root, &tag_root, &mut files)?;
        }
        let mut tags: BTreeMap<String, BTreeMap<String, Value>> = BTreeMap::new();
        for f in files {
            let (reg, tag) = split_tag_path(&f, &registries);
            let values = read_json(&tag_root.join(format!("{f}.json")))?["values"].clone();
            tags.entry(format!("minecraft:{reg}")).or_default().insert(format!("minecraft:{tag}"), values);
        }

        Ok(Self { name, version, jar, packets, synced, synced_entries, builtin, blocks, tags })
    }

    fn state_count(&self) -> u64 {
        self.blocks.values().map(|b| b.first + b.states).max().unwrap_or(0)
    }

    fn biome_count(&self) -> usize {
        self.synced_entries.get("minecraft:worldgen/biome").map_or(0, Vec::len)
    }

    fn tag_count(&self) -> usize {
        self.tags.values().map(BTreeMap::len).sum()
    }

    /// Whether the client knows the registry, so its tags go into Update Tags.
    fn networked(&self, registry: &str) -> bool {
        self.builtin.contains_key(registry) || self.synced.iter().any(|r| r == registry)
    }

    fn networked_tag_count(&self) -> usize {
        self.tags.iter().filter(|(r, _)| self.networked(r)).map(|(_, t)| t.len()).sum()
    }
}

/// Splits `worldgen/biome/is_ocean` into registry and tag, preferring the longest known registry.
fn split_tag_path<'a>(path: &'a str, registries: &HashSet<String>) -> (&'a str, &'a str) {
    let split = path.match_indices('/').map(|(i, _)| i).rfind(|&i| registries.contains(&path[..i]));
    match split.or_else(|| path.find('/')) {
        Some(i) => (&path[..i], &path[i + 1..]),
        None => ("unknown", path),
    }
}

/// Bits per entry of the direct (global) palette: `Mth.ceillog2(size)`.
fn ceil_log2(n: u64) -> u32 {
    n.max(1).next_power_of_two().trailing_zeros()
}

fn pack_format(version: &Value, kind: &str) -> String {
    let p = &version["pack_version"];
    match (p[format!("{kind}_major")].as_i64(), p[format!("{kind}_minor")].as_i64()) {
        (Some(major), Some(minor)) => format!("{major}.{minor}"),
        (Some(major), None) => major.to_string(),
        _ => p[kind].to_string(),
    }
}

/// Comma-separated list, cut off after `max` items.
fn join(items: impl IntoIterator<Item = String>, max: usize) -> String {
    let items: Vec<String> = items.into_iter().collect();
    if items.len() > max {
        format!("{} and {} more", items[..max].join(", "), items.len() - max)
    } else {
        items.join(", ")
    }
}

/// Inline-code list, cut off after `max` items.
fn list<T: Display>(items: impl IntoIterator<Item = T>, max: usize) -> String {
    join(items.into_iter().map(|i| format!("`{i}`")), max)
}

fn arrow<T: PartialEq + Display>(old: T, new: T) -> String {
    if old == new { format!("{old} (unchanged)") } else { format!("{old} → {new}") }
}

/// Lines added and removed between two normalized listings, counted as multisets.
fn line_delta(old: &[String], new: &[String]) -> (usize, usize) {
    let mut counts: HashMap<&str, i64> = HashMap::new();
    for l in old {
        *counts.entry(l).or_default() -= 1;
    }
    for l in new {
        *counts.entry(l).or_default() += 1;
    }
    let added = counts.values().filter(|&&v| v > 0).sum::<i64>() as usize;
    let removed = -counts.values().filter(|&&v| v < 0).sum::<i64>() as usize;
    (added, removed)
}

fn simple_name(class: &str) -> &str {
    class.rsplit('.').next().unwrap_or(class)
}

struct Out {
    body: String,
    glance: Vec<String>,
    impact: Vec<String>,
}

fn render(base: &DataSet, new: &DataSet, c: &Classification, origin: &str) -> Result<(String, Vec<String>)> {
    let mut o = Out { body: String::new(), glance: Vec::new(), impact: Vec::new() };
    versions(&mut o, base, new)?;
    packets(&mut o, base, new, c)?;
    fingerprints(&mut o, base, new, c)?;
    synced_registries(&mut o, base, new)?;
    builtin_registries(&mut o, base, new)?;
    blocks(&mut o, base, new)?;
    tags(&mut o, base, new)?;

    let mut md = String::new();
    writeln!(md, "# {} compared with {}\n", new.name, base.name)?;
    writeln!(md, "{origin}\n")?;
    writeln!(md, "## At a glance\n")?;
    for g in &o.glance {
        writeln!(md, "- {g}")?;
    }
    writeln!(md, "\n## Impact on Kiln\n")?;
    o.impact.push(
        "Rerun `cargo xtask codegen` after switching versions: packet ids, registries, block states and tags \
         are generated."
            .into(),
    );
    for i in &o.impact {
        writeln!(md, "- {i}")?;
    }
    writeln!(md)?;
    md.push_str(&o.body);
    Ok((md, o.glance))
}

fn versions(o: &mut Out, base: &DataSet, new: &DataSet) -> Result<()> {
    let (a, b) = (&base.version, &new.version);
    let rows = [
        ("Protocol version", a["protocol_version"].to_string(), b["protocol_version"].to_string()),
        ("World version (DataVersion)", a["world_version"].to_string(), b["world_version"].to_string()),
        ("Data pack format", pack_format(a, "data"), pack_format(b, "data")),
        ("Resource pack format", pack_format(a, "resource"), pack_format(b, "resource")),
        ("Java", a["java_version"].to_string(), b["java_version"].to_string()),
        ("Stable", a["stable"].to_string(), b["stable"].to_string()),
    ];
    writeln!(o.body, "## Versions\n")?;
    writeln!(o.body, "| | {} | {} |\n|---|---|---|", base.name, new.name)?;
    for (label, x, y) in &rows {
        writeln!(o.body, "| {label} | {x} | {y} |")?;
    }
    writeln!(o.body)?;
    o.glance.push(format!(
        "Protocol {}; world version {}; data pack format {}",
        arrow(&rows[0].1, &rows[0].2),
        arrow(&rows[1].1, &rows[1].2),
        arrow(&rows[2].1, &rows[2].2)
    ));
    if rows[1].1 != rows[1].2 {
        o.impact.push(format!(
            "DataVersion changes to {}: worlds must be upgraded with vanilla `--forceUpgrade` before Kiln loads them.",
            rows[1].2
        ));
    }
    Ok(())
}

fn packets(o: &mut Out, base: &DataSet, new: &DataSet, c: &Classification) -> Result<()> {
    let mut groups: Vec<(&str, &str)> = Vec::new();
    for p in new.packets.iter().chain(&base.packets) {
        let g = (p.state.as_str(), p.dir.as_str());
        if !groups.contains(&g) {
            groups.push(g);
        }
    }
    writeln!(o.body, "## Packets\n")?;
    writeln!(
        o.body,
        "| State | Direction | {} | {} | Added | Removed | Renumbered |\n|---|---|---|---|---|---|---|",
        base.name, new.name
    )?;
    let mut details = String::new();
    let (mut added_n, mut removed_n, mut renumbered_n) = (0, 0, 0);
    let mut unclassified = Vec::new();
    let mut implemented_removed = Vec::new();
    let mut implemented_renumbered = 0;
    for (state, dir) in groups {
        let in_group = |p: &&Packet| p.state == state && p.dir == dir;
        let old: BTreeMap<&str, i64> = base.packets.iter().filter(in_group).map(|p| (p.name.as_str(), p.id)).collect();
        let cur: BTreeMap<&str, i64> = new.packets.iter().filter(in_group).map(|p| (p.name.as_str(), p.id)).collect();
        let added: Vec<&Packet> =
            new.packets.iter().filter(in_group).filter(|p| !old.contains_key(p.name.as_str())).collect();
        let removed: Vec<&Packet> =
            base.packets.iter().filter(in_group).filter(|p| !cur.contains_key(p.name.as_str())).collect();
        let renumbered: Vec<(&Packet, i64)> = new
            .packets
            .iter()
            .filter(in_group)
            .filter_map(|p| old.get(p.name.as_str()).filter(|&&id| id != p.id).map(|&id| (p, id)))
            .collect();

        writeln!(
            o.body,
            "| {state} | {dir} | {} | {} | {} | {} | {} |",
            old.len(),
            cur.len(),
            added.len(),
            removed.len(),
            renumbered.len()
        )?;
        if added.is_empty() && removed.is_empty() && renumbered.is_empty() {
            continue;
        }
        writeln!(details, "### {state} {dir}\n")?;
        if !added.is_empty() {
            let items = added.iter().map(|p| format!("`{}` (id {})", p.name, p.id));
            writeln!(details, "- Added: {}", join(items, usize::MAX))?;
        }
        if !removed.is_empty() {
            let items = removed.iter().map(|p| format!("`{}` (was {})", p.name, p.id));
            writeln!(details, "- Removed: {}", join(items, usize::MAX))?;
        }
        if !renumbered.is_empty() {
            let items = renumbered.iter().map(|(p, old)| format!("`{}` {old}→{}", p.name, p.id));
            writeln!(details, "- Renumbered: {}", join(items, usize::MAX))?;
        }
        writeln!(details)?;

        added_n += added.len();
        removed_n += removed.len();
        renumbered_n += renumbered.len();
        unclassified.extend(added.iter().filter(|p| p.entry(c).is_none()).map(|p| p.key()));
        for p in &removed {
            if p.entry(c).is_some_and(|e| e.status == Status::Implemented) {
                implemented_removed.push(p.key());
            }
        }
        implemented_renumbered +=
            renumbered.iter().filter(|(p, _)| p.entry(c).is_some_and(|e| e.status == Status::Implemented)).count();
    }
    writeln!(o.body)?;
    o.body.push_str(&details);
    o.glance.push(format!(
        "Packets: {}; {added_n} added, {removed_n} removed, {renumbered_n} renumbered",
        arrow(base.packets.len(), new.packets.len())
    ));
    if !unclassified.is_empty() {
        o.impact.push(format!(
            "Classify {} new packet(s) in `{}` or `cargo xtask completeness` fails: {}",
            unclassified.len(),
            completeness::FILE,
            list(&unclassified, usize::MAX)
        ));
    }
    if removed_n > 0 {
        o.impact
            .push(format!("Remove {removed_n} stale entr(ies) from `{}` for the removed packets.", completeness::FILE));
    }
    if !implemented_removed.is_empty() {
        o.impact.push(format!(
            "Implemented packets removed (code must change; generated constants disappear): {}",
            list(&implemented_removed, usize::MAX)
        ));
    }
    if implemented_renumbered > 0 {
        o.impact.push(format!(
            "{implemented_renumbered} implemented packet(s) renumbered: handled by codegen, no code change."
        ));
    }
    Ok(())
}

fn fingerprints(o: &mut Out, base: &DataSet, new: &DataSet, c: &Classification) -> Result<()> {
    let (old_zip, new_zip) = (Zip::open(&base.jar)?, Zip::open(&new.jar)?);
    let old_classes = bytecode::packet_classes(&base.jar, &old_zip)?;
    let new_classes = bytecode::packet_classes(&new.jar, &new_zip)?;
    let old_keys: HashSet<String> = base.packets.iter().map(Packet::key).collect();
    let both: Vec<&Packet> = new.packets.iter().filter(|p| old_keys.contains(&p.key())).collect();
    let class_of =
        |map: &HashMap<(String, String), String>, p: &Packet| map.get(&(p.dir.clone(), p.name.clone())).cloned();

    let watched = WATCHED.iter().map(|(class, _)| class.to_string());
    let old_list: BTreeSet<String> =
        both.iter().filter_map(|p| class_of(&old_classes, p)).chain(watched.clone()).collect();
    let new_list: BTreeSet<String> = both.iter().filter_map(|p| class_of(&new_classes, p)).chain(watched).collect();
    let old_list: Vec<String> = old_list.into_iter().collect();
    let new_list: Vec<String> = new_list.into_iter().collect();
    let old_fp = bytecode::fingerprints(&base.jar, &old_zip, &old_list)?;
    let new_fp = bytecode::fingerprints(&new.jar, &new_zip, &new_list)?;

    let mut unchanged = 0;
    let mut changed = Vec::new();
    let mut unmapped = Vec::new();
    for p in &both {
        let (oc, nc) = (class_of(&old_classes, p), class_of(&new_classes, p));
        match (oc.as_ref().and_then(|k| old_fp.get(k)), nc.as_ref().and_then(|k| new_fp.get(k))) {
            (Some(a), Some(b)) if a == b => unchanged += 1,
            (Some(a), Some(b)) => changed.push((*p, nc.unwrap(), line_delta(a, b))),
            _ => unmapped.push(p.key()),
        }
    }
    let status =
        |p: &Packet| p.entry(c).map_or("unclassified".to_string(), |e| format!("{:?}", e.status).to_lowercase());

    writeln!(o.body, "## Packet class fingerprints\n")?;
    writeln!(
        o.body,
        "Normalized `javap -c -p` of each packet class and its nested classes, ignoring constant pool \
         indices and bytecode offsets. A change means the codec or other code in the class changed; \
         types shared between packets (item stacks, components, spawn info) appear under watched classes.\n"
    )?;
    writeln!(o.body, "{unchanged} of {} packets present in both versions are unchanged.\n", both.len())?;
    if !changed.is_empty() {
        writeln!(o.body, "| Packet | Class | Kiln | Lines +/− |\n|---|---|---|---|")?;
        changed.sort_by_key(|(p, _, _)| (p.entry(c).map(|e| e.status as u8), p.key()));
        for (p, class, (add, del)) in &changed {
            writeln!(o.body, "| `{}` | `{}` | {} | +{add} −{del} |", p.key(), simple_name(class), status(p))?;
        }
        writeln!(o.body)?;
    }
    if !unmapped.is_empty() {
        writeln!(o.body, "No packet class found for: {}\n", list(&unmapped, usize::MAX))?;
    }
    writeln!(
        o.body,
        "To see a change, diff `javap -c -p -cp <jar> <class>` between the two server jars \
         (`versions/*/server-*.jar` in each directory).\n"
    )?;

    writeln!(o.body, "### Watched classes\n")?;
    writeln!(o.body, "| Class | Role | Status | Lines +/− |\n|---|---|---|---|")?;
    let mut watched_changed = Vec::new();
    for (class, role) in WATCHED {
        let (status, delta) = match (old_fp.get(*class), new_fp.get(*class)) {
            (Some(a), Some(b)) if a == b => ("unchanged", String::new()),
            (Some(a), Some(b)) => {
                let (add, del) = line_delta(a, b);
                watched_changed.push(simple_name(class));
                ("changed", format!("+{add} −{del}"))
            }
            (None, Some(_)) => ("added", String::new()),
            (Some(_), None) => ("removed", String::new()),
            (None, None) => ("missing in both", String::new()),
        };
        writeln!(o.body, "| `{}` | {role} | {status} | {delta} |", simple_name(class))?;
    }
    writeln!(o.body)?;

    let implemented: Vec<String> = changed
        .iter()
        .filter(|(p, _, _)| p.entry(c).is_some_and(|e| e.status == Status::Implemented))
        .map(|(p, class, _)| format!("{} ({})", p.key(), simple_name(class)))
        .collect();
    o.glance.push(format!(
        "Packet classes: {} of {} changed ({} implemented by Kiln); watched classes changed: {}",
        changed.len(),
        both.len(),
        implemented.len(),
        if watched_changed.is_empty() { "none".to_string() } else { list(&watched_changed, usize::MAX) }
    ));
    if !implemented.is_empty() {
        o.impact.push(format!(
            "Re-check these implemented packets against the new bytecode and re-run `tools/vanilla_decode.py`: {}",
            list(&implemented, usize::MAX)
        ));
    }
    if !watched_changed.is_empty() {
        o.impact.push(format!("Review changed shared classes: {}", list(&watched_changed, usize::MAX)));
    }
    Ok(())
}

/// Added and removed entries between two lists.
fn set_diff<'a>(old: &'a [String], new: &'a [String]) -> (Vec<&'a String>, Vec<&'a String>) {
    let (o, n): (HashSet<&String>, HashSet<&String>) = (old.iter().collect(), new.iter().collect());
    (new.iter().filter(|e| !o.contains(e)).collect(), old.iter().filter(|e| !n.contains(e)).collect())
}

fn synced_registries(o: &mut Out, base: &DataSet, new: &DataSet) -> Result<()> {
    writeln!(o.body, "## Synchronized registries\n")?;
    let (added, removed) = set_diff(&base.synced, &new.synced);
    if base.synced == new.synced {
        writeln!(o.body, "Registry Data list and order unchanged ({} registries).\n", new.synced.len())?;
    } else {
        writeln!(o.body, "Registry Data list changed: {} registries.\n", arrow(base.synced.len(), new.synced.len()))?;
        if !added.is_empty() {
            writeln!(o.body, "- Added: {}", list(&added, usize::MAX))?;
        }
        if !removed.is_empty() {
            writeln!(o.body, "- Removed: {}", list(&removed, usize::MAX))?;
        }
        if added.is_empty() && removed.is_empty() {
            writeln!(o.body, "- Same registries, new order: {}", list(&new.synced, usize::MAX))?;
        }
        writeln!(o.body)?;
        o.impact.push("The synchronized registry list changed; codegen regenerates it from the new jar.".into());
    }

    let mut changed = Vec::new();
    let empty = Vec::new();
    for reg in &new.synced {
        let old = base.synced_entries.get(reg).unwrap_or(&empty);
        let cur = &new.synced_entries[reg];
        let (a, r) = set_diff(old, cur);
        if !a.is_empty() || !r.is_empty() {
            changed.push((reg, old.len(), cur.len(), a, r));
        }
    }
    if changed.is_empty() {
        writeln!(o.body, "No entries added or removed.\n")?;
    } else {
        writeln!(o.body, "| Registry | {} | {} | Added | Removed |\n|---|---|---|---|---|", base.name, new.name)?;
        for (reg, x, y, a, r) in &changed {
            writeln!(o.body, "| `{reg}` | {x} | {y} | {} | {} |", list(a, 30), list(r, 30))?;
        }
        writeln!(o.body)?;
    }
    let names: Vec<&str> = changed.iter().map(|(reg, ..)| strip(reg)).collect();
    o.glance.push(format!(
        "Synchronized registries: {}; entries changed in {}",
        arrow(base.synced.len(), new.synced.len()),
        if names.is_empty() { "none".to_string() } else { list(&names, usize::MAX) }
    ));
    Ok(())
}

fn builtin_registries(o: &mut Out, base: &DataSet, new: &DataSet) -> Result<()> {
    writeln!(o.body, "## Built-in registries\n")?;
    let old_names: Vec<String> = base.builtin.keys().cloned().collect();
    let new_names: Vec<String> = new.builtin.keys().cloned().collect();
    let (added, removed) = set_diff(&old_names, &new_names);
    writeln!(o.body, "{} registries.\n", arrow(old_names.len(), new_names.len()))?;
    if !added.is_empty() {
        let items = added.iter().map(|r| format!("`{r}` ({} entries)", new.builtin[*r].len()));
        writeln!(o.body, "- Added: {}", join(items, usize::MAX))?;
    }
    if !removed.is_empty() {
        let items = removed.iter().map(|r| format!("`{r}` ({} entries)", base.builtin[*r].len()));
        writeln!(o.body, "- Removed: {}", join(items, usize::MAX))?;
    }
    if !added.is_empty() || !removed.is_empty() {
        writeln!(o.body)?;
    }

    let mut changed = Vec::new();
    for (reg, cur) in &new.builtin {
        let Some(old) = base.builtin.get(reg) else { continue };
        let (a, r) = set_diff(old, cur);
        let old_ids: HashMap<&String, usize> = old.iter().enumerate().map(|(i, e)| (e, i)).collect();
        let renumbered = cur.iter().enumerate().filter(|(i, e)| old_ids.get(e).is_some_and(|j| j != i)).count();
        if !a.is_empty() || !r.is_empty() || renumbered > 0 {
            changed.push((reg, old.len(), cur.len(), a, r, renumbered));
        }
    }
    if changed.is_empty() {
        writeln!(o.body, "No entry changes in registries present in both versions.\n")?;
    } else {
        writeln!(
            o.body,
            "| Registry | {} | {} | Added | Removed | Renumbered |\n|---|---|---|---|---|---|",
            base.name, new.name
        )?;
        for (reg, x, y, a, r, n) in &changed {
            writeln!(o.body, "| `{reg}` | {x} | {y} | {} | {} | {n} |", list(a, 30), list(r, 30))?;
        }
        writeln!(o.body)?;
    }
    let names: Vec<&str> = changed.iter().map(|(reg, ..)| strip(reg)).collect();
    o.glance.push(format!(
        "Built-in registries: {}, {} added, {} removed; entries changed in {}",
        arrow(old_names.len(), new_names.len()),
        added.len(),
        removed.len(),
        if names.is_empty() { "none".to_string() } else { list(&names, 12) }
    ));
    Ok(())
}

fn blocks(o: &mut Out, base: &DataSet, new: &DataSet) -> Result<()> {
    let (s0, s1) = (base.state_count(), new.state_count());
    let (bits0, bits1) = (ceil_log2(s0), ceil_log2(s1));
    let (b0, b1) = (base.biome_count() as u64, new.biome_count() as u64);
    writeln!(o.body, "## Blocks\n")?;
    writeln!(o.body, "| | {} | {} |\n|---|---|---|", base.name, new.name)?;
    writeln!(o.body, "| Blocks | {} | {} |", base.blocks.len(), new.blocks.len())?;
    writeln!(o.body, "| Block states | {s0} | {s1} |")?;
    writeln!(o.body, "| Direct palette bits (block states) | {bits0} | {bits1} |")?;
    writeln!(o.body, "| Biomes | {b0} | {b1} |")?;
    writeln!(o.body, "| Direct palette bits (biomes) | {} | {} |\n", ceil_log2(b0), ceil_log2(b1))?;

    let added: Vec<String> = new
        .blocks
        .iter()
        .filter(|(k, _)| !base.blocks.contains_key(*k))
        .map(|(k, b)| format!("`{k}` ({} states)", b.states))
        .collect();
    let removed: Vec<&String> = base.blocks.keys().filter(|k| !new.blocks.contains_key(*k)).collect();
    let mut resized = Vec::new();
    let mut reshaped = Vec::new();
    let mut moved: Vec<(&String, u64, u64)> = Vec::new();
    for (k, b) in &new.blocks {
        let Some(old) = base.blocks.get(k) else { continue };
        if old.states != b.states {
            resized.push(format!("`{k}` {}→{}", old.states, b.states));
        } else if old.properties != b.properties {
            reshaped.push(k);
        }
        if old.first != b.first {
            moved.push((k, old.first, b.first));
        }
    }
    if !added.is_empty() {
        writeln!(o.body, "- Added ({}): {}", added.len(), join(added, 100))?;
    }
    if !removed.is_empty() {
        writeln!(o.body, "- Removed ({}): {}", removed.len(), list(&removed, 100))?;
    }
    if !resized.is_empty() {
        writeln!(o.body, "- State count changed ({}): {}", resized.len(), join(resized, 100))?;
    }
    if !reshaped.is_empty() {
        writeln!(o.body, "- Properties changed, same state count ({}): {}", reshaped.len(), list(&reshaped, 100))?;
    }
    match moved.iter().min_by_key(|(_, old, _)| *old) {
        Some((k, old, cur)) => writeln!(
            o.body,
            "- State ids shift from `{k}` onward (first state {old} → {cur}); {} blocks have new state ids.",
            moved.len()
        )?,
        None => writeln!(o.body, "- State ids of existing blocks are unchanged.")?,
    }
    writeln!(o.body)?;

    o.glance.push(format!(
        "Blocks: {}; block states {}; direct palette bits {}",
        arrow(base.blocks.len(), new.blocks.len()),
        arrow(s0, s1),
        arrow(bits0, bits1)
    ));
    if bits0 != bits1 || ceil_log2(b0) != ceil_log2(b1) {
        o.impact.push(format!(
            "Direct palette bits change (block states {bits0} → {bits1}, biomes {} → {}): chunk section \
             encoding must follow.",
            ceil_log2(b0),
            ceil_log2(b1)
        ));
    }
    Ok(())
}

fn tags(o: &mut Out, base: &DataSet, new: &DataSet) -> Result<()> {
    let (all0, all1) = (base.tag_count(), new.tag_count());
    let (net0, net1) = (base.networked_tag_count(), new.networked_tag_count());
    writeln!(o.body, "## Tags\n")?;
    writeln!(
        o.body,
        "{} tag files in the vanilla data pack; {} of them belong to registries the client knows and go \
         into Update Tags.\n",
        arrow(all0, all1),
        arrow(net0, net1)
    )?;
    let empty = BTreeMap::new();
    let registries: BTreeSet<&String> = base.tags.keys().chain(new.tags.keys()).collect();
    let mut rows = Vec::new();
    for reg in registries {
        let old = base.tags.get(reg).unwrap_or(&empty);
        let cur = new.tags.get(reg).unwrap_or(&empty);
        let added: Vec<&String> = cur.keys().filter(|t| !old.contains_key(*t)).collect();
        let removed: Vec<&String> = old.keys().filter(|t| !cur.contains_key(*t)).collect();
        let edited = cur.iter().filter(|(t, v)| old.get(*t).is_some_and(|ov| ov != *v)).count();
        if !added.is_empty() || !removed.is_empty() || edited > 0 {
            rows.push((reg, old.len(), cur.len(), added, removed, edited));
        }
    }
    if rows.is_empty() {
        writeln!(o.body, "No tag changes.\n")?;
    } else {
        writeln!(
            o.body,
            "| Registry | Update Tags | {} | {} | Added | Removed | Contents changed |\n|---|---|---|---|---|---|---|",
            base.name, new.name
        )?;
        for (reg, x, y, a, r, e) in &rows {
            let sent = if new.networked(reg) || base.networked(reg) { "yes" } else { "no" };
            writeln!(o.body, "| `{reg}` | {sent} | {x} | {y} | {} | {} | {e} |", list(a, 20), list(r, 20))?;
        }
        writeln!(o.body)?;
    }
    let names: Vec<&str> = rows.iter().map(|(reg, ..)| strip(reg)).collect();
    o.glance.push(format!(
        "Tags: {} (Update Tags: {}); changed in {}",
        arrow(all0, all1),
        arrow(net0, net1),
        if names.is_empty() { "none".to_string() } else { list(&names, 12) }
    ));
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn direct_palette_bits_match_mth_ceillog2() {
        assert_eq!(ceil_log2(35723), 16);
        assert_eq!(ceil_log2(32768), 15);
        assert_eq!(ceil_log2(32769), 16);
        assert_eq!(ceil_log2(65), 7);
        assert_eq!(ceil_log2(64), 6);
        assert_eq!(ceil_log2(1), 0);
    }

    #[test]
    fn tag_paths_use_the_longest_registry() {
        let regs: HashSet<String> = ["block", "worldgen/biome", "worldgen/structure"].map(String::from).into();
        assert_eq!(split_tag_path("block/mineable/pickaxe", &regs), ("block", "mineable/pickaxe"));
        assert_eq!(split_tag_path("worldgen/biome/is_ocean", &regs), ("worldgen/biome", "is_ocean"));
        assert_eq!(split_tag_path("function/load", &regs), ("function", "load"));
        assert_eq!(split_tag_path("lonely", &regs), ("unknown", "lonely"));
    }

    #[test]
    fn line_delta_counts_multisets() {
        let s = |v: &[&str]| v.iter().map(|x| x.to_string()).collect::<Vec<_>>();
        assert_eq!(line_delta(&s(&["a", "b", "b"]), &s(&["b", "c", "c"])), (2, 2));
        assert_eq!(line_delta(&s(&["a"]), &s(&["a"])), (0, 0));
    }

    #[test]
    fn pack_formats() {
        let v = serde_json::json!({ "pack_version": { "data_major": 121, "data_minor": 0, "resource_major": 97, "resource_minor": 1 } });
        assert_eq!(pack_format(&v, "data"), "121.0");
        assert_eq!(pack_format(&v, "resource"), "97.1");
        assert_eq!(pack_format(&serde_json::json!({ "pack_version": { "data": 48 } }), "data"), "48");
    }
}
