// Dumps the map color of every block state (`BlockState.getMapColor`) as run-lengths of consecutive
// state ids, as Rust source for crates/kiln-data/src/gen/map_colors.rs.
//
// usage: java -cp <server jar + libraries> tools/ExtractMapColors.java <out file>

import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.EmptyBlockGetter;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.material.MapColor;

public class ExtractMapColors {
    public static void main(String[] args) throws Exception {
        net.minecraft.SharedConstants.tryDetectVersion();
        net.minecraft.server.Bootstrap.bootStrap();
        int n = Block.BLOCK_STATE_REGISTRY.size();
        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(Path.of(args[0])))) {
            w.println("// @generated by tools/ExtractMapColors.java. Do not edit.");
            w.println();
            w.println("//! `BlockState.getMapColor` of every state: runs of consecutive state ids with the same `MapColor` id.");
            w.println();
            w.println("/// `MapColor` ids in use (`MapColor.MATERIAL_COLORS` has 64 slots).");
            int max = 0;
            for (int i = 0; i < 64; i++) if (MapColor.byId(i) != MapColor.NONE || i == 0) max = i;
            w.println("pub const MAP_COLORS: usize = " + (max + 1) + ";");
            w.println();
            w.println("/// (first state id, map color id): a run lasts to the next entry.");
            w.println("pub static MAP_COLOR_RUNS: &[(u16, u8)] = &[");
            int last = -1;
            for (int id = 0; id < n; id++) {
                BlockState s = Block.BLOCK_STATE_REGISTRY.byId(id);
                int c = s.getMapColor(EmptyBlockGetter.INSTANCE, BlockPos.ZERO).id;
                if (c != last) {
                    w.println("    (" + id + ", " + c + "),");
                    last = c;
                }
            }
            w.println("];");
            w.println();
            w.println("/// `MapColor.id` of each color (index) with its RGB `col`: (id, rgb).");
            w.println("pub static MAP_COLOR_RGB: &[(u8, u32)] = &[");
            for (int i = 0; i <= max; i++) {
                MapColor mc = MapColor.byId(i);
                w.println("    (" + i + ", 0x" + String.format("%06X", mc.col) + "),");
            }
            w.println("];");
        }
    }
}
