"""Writes crates/kiln-entity/src/gen/step_sounds.rs from the step sound dump of the vanilla game.

The dump is made by `InteractVectors.java --step-sounds` (the vanilla server calls `playStepSound` of every
living entity type on stone and reports what a listener hears, plus `getMovementEmission` and the fall sounds):

    python tools/interact_vectors.py --skip-rust --filter=--step-sounds --out <work>/wp54/mobs/step_sounds.jsonl
    python tools/gen_step_sounds.py <work>/wp54/mobs/step_sounds.jsonl crates/kiln-entity/src/gen/step_sounds.rs
"""

import json
import sys

STONE_STEP = "minecraft:block.stone.step"


def main():
    src, dst = sys.argv[1], sys.argv[2]
    rows = []
    for line in open(src, encoding="utf-8"):
        v = json.loads(line)
        first = v["steps"][0]
        if not isinstance(first, list):
            sys.exit(f"{v['type']}: {first}")
        if not first:
            step = "Step::Silent"
            source = "neutral"
        else:
            assert len(first) == 1, v["type"]
            s = first[0]
            assert s["pitch"] == 1.0, f"{v['type']}: pitch {s['pitch']}"
            source = s["source"]
            if s["name"] == STONE_STEP and abs(s["volume"] - 0.15) < 1e-6:
                step = "Step::Block"
            else:
                step = 'Step::Fixed("%s", %r)' % (s["name"], s["volume"])
        emission = {"NONE": "Emission::None", "EVENTS": "Emission::Events", "SOUNDS": "Emission::Sounds", "ALL": "Emission::All"}[v["emission"]]
        fall = v["fall"] or ["minecraft:entity.generic.small_fall", "minecraft:entity.generic.big_fall"]
        rows.append((v["type"], emission, source, step, fall))
    rows.sort()
    out = ["// @generated by tools/gen_step_sounds.py from the vanilla game's step sound dump. Do not edit.", ""]
    out.append("//! What each living entity type makes of a step: `getMovementEmission`, `playStepSound` on stone and the fall sounds.")
    out.append("")
    out.append("use super::{Emission, Step, StepRow};")
    out.append("")
    out.append("pub static STEP_ROWS: &[StepRow] = &[")
    for t, emission, source, step, fall in rows:
        out.append(f'    StepRow {{ type_name: "{t}", emission: {emission}, source: "{source}", step: {step}, fall: ("{fall[0]}", "{fall[1]}") }},')
    out.append("];")
    open(dst, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
