//! The painting variants of the vanilla datapack (`data/minecraft/painting_variant`): name, width, height
//! (in blocks) and whether `#minecraft:painting_variant/placeable` holds it.

pub const VARIANTS: &[(&str, i32, i32, bool)] = &[
    ("minecraft:alban", 1, 1, true),
    ("minecraft:aztec", 1, 1, true),
    ("minecraft:aztec2", 1, 1, true),
    ("minecraft:backyard", 3, 4, true),
    ("minecraft:baroque", 2, 2, true),
    ("minecraft:bomb", 1, 1, true),
    ("minecraft:bouquet", 3, 3, true),
    ("minecraft:burning_skull", 4, 4, true),
    ("minecraft:bust", 2, 2, true),
    ("minecraft:cavebird", 3, 3, true),
    ("minecraft:changing", 4, 2, true),
    ("minecraft:cotan", 3, 3, true),
    ("minecraft:courbet", 2, 1, true),
    ("minecraft:creebet", 2, 1, true),
    ("minecraft:dennis", 3, 3, true),
    ("minecraft:donkey_kong", 4, 3, true),
    ("minecraft:earth", 2, 2, false),
    ("minecraft:endboss", 3, 3, true),
    ("minecraft:fern", 3, 3, true),
    ("minecraft:fighters", 4, 2, true),
    ("minecraft:finding", 4, 2, true),
    ("minecraft:fire", 2, 2, false),
    ("minecraft:graham", 1, 2, true),
    ("minecraft:humble", 2, 2, true),
    ("minecraft:kebab", 1, 1, true),
    ("minecraft:lowmist", 4, 2, true),
    ("minecraft:match", 2, 2, true),
    ("minecraft:meditative", 1, 1, true),
    ("minecraft:orb", 4, 4, true),
    ("minecraft:owlemons", 3, 3, true),
    ("minecraft:passage", 4, 2, true),
    ("minecraft:pigscene", 4, 4, true),
    ("minecraft:plant", 1, 1, true),
    ("minecraft:pointer", 4, 4, true),
    ("minecraft:pond", 3, 4, true),
    ("minecraft:pool", 2, 1, true),
    ("minecraft:prairie_ride", 1, 2, true),
    ("minecraft:sea", 2, 1, true),
    ("minecraft:skeleton", 4, 3, true),
    ("minecraft:skull_and_roses", 2, 2, true),
    ("minecraft:stage", 2, 2, true),
    ("minecraft:sunflowers", 3, 3, true),
    ("minecraft:sunset", 2, 1, true),
    ("minecraft:tides", 3, 3, true),
    ("minecraft:unpacked", 4, 4, true),
    ("minecraft:void", 2, 2, true),
    ("minecraft:wanderer", 1, 2, true),
    ("minecraft:wasteland", 1, 1, true),
    ("minecraft:water", 2, 2, false),
    ("minecraft:wind", 2, 2, false),
    ("minecraft:wither", 2, 2, true),
];
